name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Install framebuffer (xvfb) and Chromium"
        run: |
          sudo apt-get update
          sudo apt-get install chromium-browser xvfb
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: "Install dependencies and build NPM package"
        run: npm run build-package
      - name: "Run JS tests"
        run: xvfb-run npm test
